[UP] New architecture for project

diff --git a/.github/workflows/deployment_prod.yml b/.github/workflows/deployment_prod.yml
--- a/.github/workflows/deployment_prod.yml
+++ b/.github/workflows/deployment_prod.yml
@@ -12,9 +12,10 @@ jobs:
       matrix:
         service: [api, front]
     steps:
-      - name: Checkout
+      - name: Checkout Code
         uses: actions/checkout@v2
-      - name: Install dependencies and test
+      
+      - name: Install Dependencies and Run Tests
         working-directory: my_memo_master_${{ matrix.service }}
         run: |
           npm install
@@ -25,20 +26,11 @@ jobs:
     needs: test
     if: failure()
     steps:
-      - name: Send message to Discord
+      - name: Send Test Failure Notification to Discord
         run: |
-          URLS=(
-            "https://media1.tenor.com/m/4CtiBiTdmioAAAAC/vilebrequin-sylvain.gif"
-            "https://media1.tenor.com/m/GgnOYuwPdAIAAAAC/vilebrequin-sylvain.gif"
-            "https://media1.tenor.com/m/OlLPEZbtPEYAAAAd/vilebrequin-vilebrequin-telemerding.gif"
-            "https://media1.tenor.com/m/-o0dTiU5Ow4AAAAd/vilebrequin-vilebrequin-cpt.gif"
-            "https://media1.tenor.com/m/eMOeGcx_o54AAAAd/crash-bus.gif"
-            "https://media1.tenor.com/m/0y5lOt_Y450AAAAd/vilebrequin-vilebrequin-cpt.gif"
-            "https://media1.tenor.com/m/hoRt31ZDmPEAAAAC/vilebrequin-sylvain.gif"
-            "https://media1.tenor.com/m/gD2lZPrYVW4AAAAC/vilebrequin-vilebrequin-sylvain-levy.gif"
-            "https://media1.tenor.com/m/sBEng5B5vbwAAAAC/cat-cats.gif"
-            "https://media1.tenor.com/m/1c70Jy7WZI8AAAAd/cat.gif"
-            "https://media1.tenor.com/m/GElyvue_13cAAAAd/april-fools-joke.gif"
+          URLS=( 
+            "https://media1.tenor.com/m/4CtiBiTdmioAAAAC/vilebrequin-sylvain.gif" 
+            "https://media1.tenor.com/m/GgnOYuwPdAIAAAAC/vilebrequin-sylvain.gif" 
           )
           RANDOM_URL=${URLS[$RANDOM % ${#URLS[@]}]}
           BRANCH_NAME=${GITHUB_REF##*/}
@@ -51,15 +43,11 @@ jobs:
     needs: test
     if: success()
     steps:
-      - name: Send success message to Discord
+      - name: Send Test Success Notification to Discord
         run: |
-          URLS=(
-            "https://media1.tenor.com/m/BhPivX5RaGgAAAAd/vilebrequin-vilbrequin.gif"
-            "https://media1.tenor.com/m/-c-taOTKNN8AAAAd/vilebrequin-sylvain.gif"
-            "https://media1.tenor.com/m/4Nxe3sCkjVcAAAAd/vilebrequin-vilbrequin.gif"
-            "https://media1.tenor.com/m/uPogt0rnqKoAAAAd/rosycheeks-approved.gif"
-            "https://media1.tenor.com/m/eAwDugg8aBgAAAAd/kitty-meow.gif"
-            "https://media1.tenor.com/m/wjS2sXen8iMAAAAd/stonks-up-stongs.gif"
+          URLS=( 
+            "https://media1.tenor.com/m/BhPivX5RaGgAAAAd/vilebrequin-vilbrequin.gif" 
+            "https://media1.tenor.com/m/uPogt0rnqKoAAAAd/rosycheeks-approved.gif" 
           )
           RANDOM_URL=${URLS[$RANDOM % ${#URLS[@]}]}
           BRANCH_NAME=${GITHUB_REF##*/}
@@ -68,7 +56,7 @@ jobs:
           ${{ secrets.DISCORD_LOG }}
 
   sonar_analysis:
-    name: SonarQube Analysis
+    name: Run SonarQube Analysis
     runs-on: ubuntu-latest
     needs: test
     steps:
@@ -76,7 +64,7 @@ jobs:
         uses: actions/checkout@v2
         with:
           fetch-depth: 0
-
+      
       - name: Run SonarQube Scan
         uses: sonarsource/sonarqube-scan-action@v3
         env:
@@ -84,45 +72,15 @@ jobs:
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
 
   sonar_analysis_failure:
-    name: Send message to Discord
+    name: Notify SonarQube Failure
     runs-on: ubuntu-latest
     needs: sonar_analysis
     if: failure()
     steps:
-      - name: Send message to Discord
+      - name: Send SonarQube Failure Notification to Discord
         run: |
-          URLS=(
-            "https://media1.tenor.com/m/4CtiBiTdmioAAAAC/vilebrequin-sylvain.gif"
-            "https://media1.tenor.com/m/GgnOYuwPdAIAAAAC/vilebrequin-sylvain.gif"
-            "https://media1.tenor.com/m/OlLPEZbtPEYAAAAd/vilebrequin-vilebrequin-telemerding.gif"
-            "https://media1.tenor.com/m/-o0dTiU5Ow4AAAAd/vilebrequin-vilebrequin-cpt.gif"
-            "https://media1.tenor.com/m/eMOeGcx_o54AAAAd/crash-bus.gif"
-            "https://media1.tenor.com/m/0y5lOt_Y450AAAAd/vilebrequin-vilebrequin-cpt.gif"
-            "https://media1.tenor.com/m/hoRt31ZDmPEAAAAC/vilebrequin-sylvain.gif"
-          )
-          RANDOM_URL=${URLS[$RANDOM % ${#URLS[@]}]}
-          BRANCH_NAME=${GITHUB_REF##*/}
           curl -X POST -H "Content-Type: application/json" \
-          -d "{\"content\": \"SonarQube analysis failed on branch $BRANCH_NAME! $RANDOM_URL\"}" \
-          ${{ secrets.DISCORD_LOG }}
-
-  sonar_analysis_success:
-    name: Send message to Discord
-    runs-on: ubuntu-latest
-    needs: sonar_analysis
-    if: success()
-    steps:
-      - name: Send message to Discord
-        run: |
-          URLS=(
-            "https://media1.tenor.com/m/SYbQQkWKTJUAAAAd/vilebrequin-vilebrequin-winamax.gif"
-            "https://media1.tenor.com/m/2C6IrDSSZ4EAAAAd/vilebrequin-vilebrequin-winamax.gif"
-            "https://media1.tenor.com/m/Fl1OdPlcQ20AAAAC/vilebrequin-vilebrequin-dos-d-ane.gif"
-            "https://media1.tenor.com/m/LbNXxiA2KlgAAAAC/vilebrequin-sylvain.gif"
-          )
-          RANDOM_URL=${URLS[$RANDOM % ${#URLS[@]}]}
-          curl -X POST -H "Content-Type: application/json" \
-          -d "{\"content\": \"Project is ready to build and deploy! $RANDOM_URL\"}" \
+          -d "{\"content\": \"SonarQube analysis failed on branch $GITHUB_REF!\"}" \
           ${{ secrets.DISCORD_LOG }}
 
   build_and_deploy:
@@ -133,26 +91,33 @@ jobs:
     steps:
       - name: Checkout Code
         uses: actions/checkout@v2
-      - name: Set up SSH
+
+      - name: Set up SSH for Deployment
         uses: webfactory/ssh-agent@v0.5.3
         with:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+
       - name: Deploy to VPS
         run: |
+          # Sync files to VPS
           rsync -avz --exclude-from='.scpignore' -e "ssh -o StrictHostKeyChecking=no" . root@${{ secrets.VPS_IP }}:/var/www/html/mymemomaster
+          
+          # Execute remote commands to build and run Docker Compose
           ssh root@${{ secrets.VPS_IP }} << 'EOF'
             set -e
-            # Vérifier les dépendances Node.js
-            if [ -d "/var/www/html/mymemomaster/my_memo_master_api" ]; then
-              cd /var/www/html/mymemomaster/my_memo_master_api
-              npm install
-            fi
-            if [ -d "/var/www/html/mymemomaster/my_memo_master_front" ]; then
-              cd /var/www/html/mymemomaster/my_memo_master_front
-              npm install
-            fi
-            # Déployer avec Docker Compose
+
+            # Navigate to project directory
             cd /var/www/html/mymemomaster
+
+            # Ensure Docker Compose is properly configured
+            if [ -f "docker-compose.yml" ]; then
+              echo "Docker Compose file exists. Proceeding with deployment."
+            else
+              echo "ERROR: docker-compose.yml not found!"
+              exit 1
+            fi
+
+            # Pull new images and restart services
             docker-compose down
             docker-compose build
             docker-compose up -d
@@ -163,15 +128,10 @@ jobs:
     needs: build_and_deploy
     if: failure()
     steps:
-      - name: Send message to Discord
+      - name: Notify Deployment Failure
         run: |
-          URLS=(
-            "https://media1.tenor.com/m/asSa0XkcXXwAAAAd/rocket-failure-explode.gif"
-          )
-          RANDOM_URL=${URLS[$RANDOM % ${#URLS[@]}]}
-          BRANCH_NAME=${GITHUB_REF##*/}
           curl -X POST -H "Content-Type: application/json" \
-          -d "{\"content\": \"deploy failed! $RANDOM_URL\"}" \
+          -d "{\"content\": \"Deployment failed on branch $GITHUB_REF!\"}" \
           ${{ secrets.DISCORD_LOG }}
 
   build_success:
@@ -179,13 +139,8 @@ jobs:
     needs: build_and_deploy
     if: success()
     steps:
-      - name: Send success message to Discord
+      - name: Notify Deployment Success
         run: |
-          URLS=(
-            "https://media1.tenor.com/m/NvmqvFu5FPIAAAAd/agile-rocket.gif"
-          )
-          RANDOM_URL=${URLS[$RANDOM % ${#URLS[@]}]}
-          BRANCH_NAME=${GITHUB_REF##*/}
           curl -X POST -H "Content-Type: application/json" \
-          -d "{\"content\": \"deploy success! $RANDOM_URL\"}" \
+          -d "{\"content\": \"Deployment succeeded on branch $GITHUB_REF!\"}" \
           ${{ secrets.DISCORD_LOG }}
